#+TITLE: Chicken with peppers
# Adapted from [[https://icook.tw/recipes/264233][icook.tw]]

* Reconstitute dried shiitake
- 5 shiitake mushrooms
- hot water

Submerge the dried mushrooms in hot water, and set aside for at least 10 minutes. Do not discard the water.

* Marinade chicken
- 4 chicken thighs, in 2 inch pieces
- 1 tbsp shaoxing wine
- 2 tsp corn starch
- pinch of salt
- pinch of ground pepper

Combine and set aside to marinade for 15 minutes.


* Veggies
- 2 bell peppers, in 2 inch pieces
- 3 dried chili peppers
- 1 potato, peeled, in 1 inch cubes

Cut the reconstituted mushrooms in quarters and save the soaking water.

* In a wok
- 2 tbsp oil
- 3 tbsp sugar/rock sugar
- 1 tbsp ground white pepper
- 2 tbsp light soy sauce
- 2 tbsp shaoxing wine
- 2 tsp salt
- 10 sliced ginger

In a wok, on medium-low to low heat, add oil and sugar until melted and caramelized. Add chicken thighs and toss until well-coated and brown. Then add shaoxing wine, followed by ginger, chili peppers, and soy sauce. Stir-fry for 10 seconds to combine.

Add Mushroom soaking water to cover the chicken, then add in the mushrooms, white pepper, and salt. Cover and simmer for 10 minutes, then add the potatoes and simmer for another 10 minutes, or until the potato chunks are almost cooked to your liking. Expect to have about half of the soup remaining.

Taste for seasoning and add soy sauce if needed. Stir in the bell peppers and stir-fry until the peppers are cooked through.

* To serve
Serve with medium-grain rice, preferably with a side of chinese greens.
