#+TITLE: Turkish Meatballs
# Adapted from [[https://www.allrecipes.com/recipe/280481/bobs-kabobs/][Chef John]]

* Spiced meatballs
- 2 tsp ground cumin
- 1/2 tsp ground coriander
- 2 tsp Aleppo pepper
- 3/2 tsp kosher salt
- 1 pinch cayenne pepper
- 1 pinch ground cinnamon
- 1 lb ground lamb
- 2 tbsp cold water

Combine spices in a bowl, and thoroughly mix 2/3 of the spice blend with the lamb and cold water. Chill the lamb in the fridge for about 1 hour.

* Yogurt sauce
- 1 cup greek yogurt
- 2 cloves garlic, crushed
- 2 tbsp minced parsley
- 1 tbsp lemon juice
- 1/4 cup water

Mix until well-combined, then set aside in the fridge.

* Spice sprinkle
- 1 tsp ground sumac

Combine the remaining 1/3 of the spice blend with the ground sumac.

* Meatballs
Take out the lamb from the fridge and shape into 8 oval shaped meatballs, then sprinkle some spices on top.
Cook until browned and firm, with a thermometer reading at least 135 degrees F.

* To serve
Serve the lamb meatballs hot with cold yogurt sauce. Also good with cucumber salad, grilled tomatoes and hatch chilies.
